//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace www.jseasy.com.cn.crm2011.Wechat2CRMPlugin.Plugins.SendWechatService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Customer", ConfigurationName="SendWechatService.CustomerPort")]
    public interface CustomerPort {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Customer#Customer#serviceMessageSendInterface", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="serviceMessageSendInterface")]
        string serviceMessageSendInterface(string imgid, string token, string wechatid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Customer#Customer#GroupMessageSendInterface", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="GroupMessageSendInterface")]
        string GroupMessageSendInterface(string imgid, string token, string groupid);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:Customer#Customer#curlGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="curlGet")]
        string curlGet(string url, string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerPortChannel : www.jseasy.com.cn.crm2011.Wechat2CRMPlugin.Plugins.SendWechatService.CustomerPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerPortClient : System.ServiceModel.ClientBase<www.jseasy.com.cn.crm2011.Wechat2CRMPlugin.Plugins.SendWechatService.CustomerPort>, www.jseasy.com.cn.crm2011.Wechat2CRMPlugin.Plugins.SendWechatService.CustomerPort {
        
        public CustomerPortClient() {
        }
        
        public CustomerPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string serviceMessageSendInterface(string imgid, string token, string wechatid) {
            return base.Channel.serviceMessageSendInterface(imgid, token, wechatid);
        }
        
        public string GroupMessageSendInterface(string imgid, string token, string groupid) {
            return base.Channel.GroupMessageSendInterface(imgid, token, groupid);
        }
        
        public string curlGet(string url, string data) {
            return base.Channel.curlGet(url, data);
        }
    }
}
